### ISSUE TITLE
no release version.

### ISSUE THREAD

**Issue by yoya** [smartnews/yoya-thumber#18]
I think it better to set a version on this product.
- https://github.com/smartnews/yoya-thumber/releases

for example.

- v1.0
- v1.0.0
 or
- 1.0
- 1.0.0
 etc...

**Comment by firewood** [comment]
I feel `v1.0.0` is the most commonly used.

**Comment by yoya** [comment]
thank you.
https://github.com/smartnews/yoya-thumber/releases/tag/v1.0.0
